// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGxqYiE70nwQkT4Zv2mv1t08Kc7nrfSgc',
    appId: '1:480177772801:web:b41567c5ee976a26d96300',
    messagingSenderId: '480177772801',
    projectId: 'rocakidsarmenia-7935b',
    authDomain: 'rocakidsarmenia-7935b.firebaseapp.com',
    storageBucket: 'rocakidsarmenia-7935b.firebasestorage.app',
    measurementId: 'G-NBPRE3KNX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyR2qu4AjqusqV8e-NIuyYZqEudGP1Rg0',
    appId: '1:480177772801:android:75670423899004e8d96300',
    messagingSenderId: '480177772801',
    projectId: 'rocakidsarmenia-7935b',
    storageBucket: 'rocakidsarmenia-7935b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnAkavKzT3O8Fy7AyQJP_dwxKUvbBrAO0',
    appId: '1:480177772801:ios:cfac13b989c8be76d96300',
    messagingSenderId: '480177772801',
    projectId: 'rocakidsarmenia-7935b',
    storageBucket: 'rocakidsarmenia-7935b.firebasestorage.app',
    iosBundleId: 'com.konektu.rocakids',
  );
}
